[package]
name = "mohan"
version = "0.0.18"
authors = ["hello@organism.org"]
description = "Shared Types & Utils"
license = "Apache-2.0"
edition = "2018"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
parking_lot = {version = "0.9", features = ["deadlock_detection"]}
failure = "0.1"
rand = "0.6"
zeroize = "0.9.3"
rand_core = { version = "0.4", default-features = false }
byteorder = "1"
bytes = "0.4"
curve25519-dalek = { version = "1.2", features = ["serde", "alloc"] }
blake2b_simd = "0.5"


[dev-dependencies]
quickcheck = "0.8"
chrono = { version = "0.4", default-features = false }
hex = "0.3"
