[package]
name = "mohan"
version = "0.0.2"
authors = ["hello@organism.org"]
description = "Shared Types & Utils"
license = "Apache-2.0"
edition = "2018"



[dependencies]
serde = { version = "1.0", features = ["derive"] }
parking_lot = {version = "0.7", features = ["deadlock_detection"]}
bincode = { version = "1.*", features = ["i128"] }
blake2b_simd = "0.5"
chacha20-poly1305-aead = { version = "0.1.2", features = ["simd_asm", "simd", "simd_opt"] }
clear_on_drop = "0.2"
failure = "0.1"
rand = "0.6"
zeroize = "0.9"
tai64 = "2"

# Builtin Types
fixed-hash = { version = "0.3", default-features = true }
uint = { git = "https://github.com/paritytech/parity-common", version = "0.8", default-features = true }

# Reexports
merlin = "1.1.0"
bech32 = "0.6"
bytes = "0.4.12"


[dev-dependencies]
serde_json = "1.0"