[package]
name = "mohan"
version = "0.0.29"
authors = ["hello@organism.org"]
description = "Shared Types & Utils"
license = "Apache-2.0"
edition = "2018"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
parking_lot = {version = "0.9", features = ["deadlock_detection"]}
failure = "0.1"
zeroize = { version = "1.0.0-pre", features = ["zeroize_derive"] }
byteorder = "1"
bytes = "0.4"
curve25519-dalek = { version = "1.2", features = ["serde", "alloc"] }
blake2b_simd = "0.5"
rayon = "1.1"

[dependencies.rand]
version = "0.7.*"
default-features = false
optional = true
features = []

[dependencies.rand_core]
version = "0.5.*" 
default-features = false


[features]
default = ["rand"] 


[dev-dependencies]
quickcheck = "0.8"
chrono = { version = "0.4", default-features = false }
hex = "0.3"
bacteria = "0.0.5"